export const mockOrders = [
    {
      id: 1,
      date: "2025-04-22T09:00:00Z",
      totalAmount: 150000,
      note: "Khách mang về",
      staffId: 5,
      staffName: "Nguyễn Văn A",
      paymentMethodId: 1,
      paymentMethod: "Tiền mặt",
      status: "Đang xử lý",
    },
    {
      id: 2,
      date: "2025-04-22T14:00:00Z",
      totalAmount: 245000,
      note: "Ship Grab",
      staffId: 6,
      staffName: "Trần Thị B",
      paymentMethodId: 3,
      paymentMethod: "Momo",
      status: "Đã giao",
    },
    {
      id: 3,
      date: "2025-04-21T17:30:00Z",
      totalAmount: 105000,
      note: "Khách thân quen - giảm 10%",
      staffId: 5,
      staffName: "Nguyễn Văn A",
      paymentMethodId: 2,
      paymentMethod: "Chuyển khoản",
      status: "Đã hủy",
    },
  ];
  